version: '3'

services:
  visualizador:
    image: dockersamples/visualizer
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 8080:8080
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager

  static-web:
    image: docker1971/front-image-docker
    ports:
     - "8000:80"
